#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
#
# Correct the client-originated ASP Tickle generated by the AFP-over-DDP shim.
#
# Netatalk/libatalk sends ASP tickles to the peer session endpoint with user
# bytes {ASPFUNC_TICKLE, sid, 0, 0}, response_count=0, timeout=0, tries=1,
# and no ATP_XO flag.  The original shim sent tickles to the NBP listener
# socket and reused the AFP command sequence in bytes 2-3.  Classic servers
# can therefore age out an otherwise busy session during long transfers.
#
# Debian Jessie / Python 3.4 compatible.

from __future__ import print_function

import io
import os
import sys

MARKER = "GLOBALTALK ASP SESSION TICKLE R2"


def die(msg):
    raise SystemExit("apply_asp_session_tickle_r2: " + msg)


def read_text(path):
    with io.open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_text(path, text):
    with io.open(path, "w", encoding="utf-8") as f:
        f.write(text)


def function_span(text, signature):
    start = text.find(signature)
    if start < 0:
        die("function not found: {}".format(signature))

    brace = text.find("{", start)
    if brace < 0:
        die("opening brace not found: {}".format(signature))

    depth = 0
    i = brace
    state = "code"

    while i < len(text):
        c = text[i]
        n = text[i + 1] if i + 1 < len(text) else ""

        if state == "code":
            if c == '"':
                state = "string"
            elif c == "'":
                state = "char"
            elif c == "/" and n == "/":
                state = "linecomment"
                i += 1
            elif c == "/" and n == "*":
                state = "blockcomment"
                i += 1
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return start, i + 1
        elif state == "string":
            if c == "\\":
                i += 1
            elif c == '"':
                state = "code"
        elif state == "char":
            if c == "\\":
                i += 1
            elif c == "'":
                state = "code"
        elif state == "linecomment":
            if c == "\n":
                state = "code"
        elif state == "blockcomment":
            if c == "*" and n == "/":
                state = "code"
                i += 1
        i += 1

    die("unterminated function: {}".format(signature))


def main():
    if len(sys.argv) != 2:
        die("usage: apply_asp_session_tickle_r2.py NETATALK_CLIENT_TREE")

    root = os.path.abspath(sys.argv[1])
    path = os.path.join(root, "lib", "asp_transport.c")

    if not os.path.isfile(path):
        die("missing {}".format(path))

    text = read_text(path)

    if MARKER in text:
        print("ASP session tickle R2 already applied: {}".format(path))
        return

    start, end = function_span(text, "int asp_transport_tickle(")

    replacement = r'''int asp_transport_tickle(struct afp_server *server)
{
    struct afpc_asp *ctx = ctx_of(server);
    struct atp_block atpb;
    struct sockaddr_at target;
    unsigned char request[ASP_HDRSIZ];

    if (!ctx || !ctx->session_open || !ctx->atp) {
        errno = ENOTCONN;
        return -1;
    }

    /* GLOBALTALK ASP SESSION TICKLE R2
     * Mirror libatalk asp_tickle(): tickle the server's session endpoint,
     * not its NBP/listener socket.  ASP tickles have zero user bytes 2-3,
     * request no ATP response, are not XO transactions, and are sent once. */
    memset(&atpb, 0, sizeof(atpb));
    request[0] = ASPFUNC_TICKLE;
    request[1] = ctx->sid;
    request[2] = 0;
    request[3] = 0;

    target = ctx->session;
    atpb.atp_saddr = &target;
    atpb.atp_sreqdata = (char *)request;
    atpb.atp_sreqdlen = sizeof(request);
    atpb.atp_sreqto = 0;
    atpb.atp_sreqtries = 1;

    if (atp_sreq(ctx->atp, &atpb, 0, 0) < 0) {
        return -1;
    }

    return 0;
}'''

    text = text[:start] + replacement + text[end:]
    write_text(path, text)

    print("Applied ASP session tickle R2: {}".format(path))
    print("  destination: server session socket")
    print("  ATP: response_count=0 timeout=0 tries=1 flags=0")


if __name__ == "__main__":
    main()
